### ISSUE TITLE
[NOTABUG] Success on Arch Linux

### ISSUE THREAD

**Issue by Yardanico** [rozniak/xfce-winxp-tc#88] opened 2021-11-30 02:32 UTC
Hello! I saw your post on r/unixporn some time ago and was very impressed. I've decided to try using your theme on Arch, and after some fiddling around succeeded.

Basically, I've installed `dpkg` (available in the official Arch repo), and then just called all the build scripts that you have. I had to remove the missing packages check in all the scripts (I've ensured that I installed all necessary packages manually). After I've built the .deb files I converted them to Arch packages via `debtap` (I could've just installed the packages directly with `dpkg` but that's bad since it circumvents Arch's own package system). I had to change a few paths because they're different in Arch:

`wintc-comgtk.pc.in` - changed `pkgconfigdir` to `pkgconfigdir=/usr/lib/pkgconfig`
`wintc-exec.pc.in` - same as above, `pkgconfigdir=/usr/lib/pkgconfig`
`packplug.sh` in `packaging/deb/panel` - `pkg_plug_dir` to `pkg_plug_dir="${PKG_DIR}/usr/lib/xfce4/panel/plugins"`
`debian-control` in `themes/luna/blue` - removed the `Depends` line (debtap didn't seem to successfully translate the dependencies).

After that, I built `libs` and installed the converted Arch packages (they need to be installed first because they're used in shell and programs), and built + installed all other stuff.

The end result is this (click the image to view it in full resolution):
![image](https://user-images.githubusercontent.com/21169548/143974877-ed40a866-59e7-47e3-b4f4-2e8cc1172160.png)

P.S.: The notifications bar looks like that because I changed the background image in Panel Preferences -> Appearance to the one that has the same shade (it did take some time to experiment though). If someone wants the image, it's this (I've used it with the panel row size of 30 pixels):
![imagef3fg3](https://user-images.githubusercontent.com/21169548/143975061-5c5a236a-896e-485f-93f2-7ce53e709b42.png)

I know that the way I've did it is really dirty, but it works :) Maybe someone could make proper PKGBUILDs in the future, but this is good enough for me for now.

Also, I've found a document that might be a bit useful for you - [Windows XP Visual Guidelines](http://interface.free.fr/Archives/GUI_Xp.pdf)

**Comment by Yardanico** [comment] 2021-11-30 02:33
Also, wanted to know - is this a known bug or it's a regression on the latest GTK or XFCE?
(the buttons on the bottom specifically)
![image](https://user-images.githubusercontent.com/21169548/143975355-6976540e-7db2-4984-85f3-ff246b6eff7a.png)

**Comment by rozniak** [comment] 2021-12-06 00:36
Nice work! Sorry I'm away from my main computer for another week so haven't had a chance to properly look at stuff.

About the panel background - did the taskbar background image not get applied by the Luna theme?

And regarding the XFCE settings dialog - it's some regression with the latest GTK 3 that caused the CSD styles to break. For me on XFWM4/XFCE when dragging the window around there's some glitchiness with the rounded corners too on the Luna theme'd CSD windows. It worked fine on the GTK 3 shipped with Debian 10, but not in the version in Debian 11, it needs looking into (which sucks because the CSD styles aren't fun tbh :weary: )

I hope the scripts were of help even if they are .deb only for the meantime. :grin: Thank you for your notes.

**Comment by daemonspudguy** [comment] 2022-05-21 23:21
The AUR has a version of libxfce4ui that was forked from the latest version, but doesn't use the CSD framework.

**Comment by rozniak** [comment] 2022-05-21 23:32
The regressions mentioned above about CSD have since been fixed btw - obviously CSD is never going to look 'perfect' but it doesn't look totally scuffed like that screenshot anymore. :grin:

**Comment by rozniak** [comment] 2023-06-30 00:47
Arch Linux receiving packaging port via issue #182 - under testing currently soon to be merged

**Closed by rozniak** 2023-06-30 00:47 UTC
Labels: needs-thought, distro-archlinux
