### ISSUE TITLE
Build fails on Debian 12

### ISSUE THREAD

**Issue by ghost** [rozniak/xfce-winxp-tc#263] opened 2024-01-06 08:34 UTC
Hi there!

Lovely theme! I'd love to use it but the build fails on Debian.

When I run './chkdeps.sh' it outputs this error:

```
Traceback (most recent call last):
  File "/home/toquita/Downloads/xfce-winxp-tc-master/tools/bldutils/depmap/depmap.py", line 85, in <module>
    main()
  File "/home/toquita/Downloads/xfce-winxp-tc-master/tools/bldutils/depmap/depmap.py", line 66, in main
    raise ValueError(f"Invalid dep: {dep}")
ValueError: Invalid dep: ../../deps
Failed to map dependencies.
```

I'm not a programmer so I don't know what's the issue or how to solve it. Can you help me get this built? :)
Also, I wonder if it would be feasible for you to provide built packages for the distros you support. That would be lovely for newbs.

Cheers!

**Comment by rozniak** [comment] 2024-01-15 17:29
Sorry I've been away for a while but am back now.

That is very strange, are you able to send a pic of the full terminal stuff ? Not really sure what might be going on here.

> Also, I wonder if it would be feasible for you to provide built packages for the distros you support. That would be lovely for newbs.

One day yeah, #81 is still around, there are still things I would like to get done before putting out any form of precompiled release tho.

**Comment by Fabxx** [comment] 2024-01-16 16:35
Alternatively you can open the script on a text editor and check the package names to install through apt

**Comment by rozniak** [comment] 2024-01-30 16:42
Closing because OP has deleted their account

**Closed by rozniak** 2024-01-30 16:42 UTC
Labels: question, distro-debian

**Comment by rozniak** [comment] 2025-02-15 17:30
The cause of the problem was identified as symlinks being treated as normal files after the project was downloaded via GitHub's ZIP feature.

Fixed in https://github.com/rozniak/xfce-winxp-tc/commit/b76d9d6067dc087cbfd81fbed561d49754ad9420
