### ISSUE TITLE
Include Wine category in All Programs flyout

### ISSUE THREAD

**Issue by lunakittyyy** [rozniak/xfce-winxp-tc#388] opened 2024-12-02 09:14 UTC
In many other desktop environments, including KDE Plasma, if you have any Wine applications that have created Start menu items, a special category gets created in the DE's application launcher including a launcher for the Windows application.

This would be very nice for WinXP TC's custom Start menu in the taskband.

**Comment by lunakittyyy** [comment] 2024-12-02 09:18
It seems the .desktop files for this are located in ``~/.local/share/applications/wine/``

**Comment by rozniak** [comment] 2024-12-02 12:06
I won't be able to look at this until the evening perhaps, if you want to have a look in the meantime - this file is responsible for filtering down the *All Programs* groups:

https://github.com/rozniak/xfce-winxp-tc/blob/master/shell/taskband/res/start-menu.menu

Have a look in the desktop entries for those programs installed via WINE to find out what category applies to them. I'm guessing it'll be X-WINE or something like that. :thinking:

**Comment by rozniak** [comment] 2024-12-07 10:51
I just had a look via installing *Super Collapse!* and no, there is no category in the desktop entries. Looks like it might be possible to just include a directory tree in the search: https://specifications.freedesktop.org/menu-spec/latest/legacy-hierarchies.html

**Comment by rozniak** [comment] 2024-12-07 14:02
Trying to figure this out because nothing I define in `start-menu.menu` is showing the WINE submenu. Even just pinching XFCE's included one doesn't work even though the WINE submenu does show when under `xfce4-panel`. :confounded:

**Comment by rozniak** [comment] 2024-12-07 15:11
Okay, after looking through the `libgarcon` source code, I found out the problem. `<DefaultMergeDirs/>` will result in `$XDG_CONFIG_HOME/menus/<menu filename>-merged` being added to the merge dirs. So the filename for the menu *must* be `applications.menu` for this to work properly.

See: https://gitlab.xfce.org/xfce/garcon/-/blob/master/garcon/garcon-menu-merger.c?ref_type=heads#L551

I'm not entirely sure whether this is to be considered a bug or not? It seems weird to have the filename be part of the API contract, which is undocumented... but I cannot find anything in the FreeDesktop spec that describes the intended behaviour. It literally just says "default merge directories" and never what those are, at least that I can see.

In any case, problem solved - I will push a patch to rename `start-menu.menu` --> `applications.menu` and include the `<DefaultMergeDirs/>` node.

**Closed** 2024-12-07 15:14 UTC
Labels: bug, program-taskband
